# Generated by Django 5.0.6 on 2024-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_slug',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
